#!/bin/bash
# Quick start guide for running queries
# Copy this file and modify as needed for your workflow

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
QUERIES_DIR="${PROJECT_ROOT}/scripts/queries"
DB="${PROJECT_ROOT}/data/videos.db"

echo "📊 Database Query Scripts - Quick Reference"
echo "============================================"
echo ""
echo "Run any query from the project root:"
echo ""
echo "Quick commands:"
echo ""
echo "1. Database Overview:"
echo "   sqlite3 -header -column $DB < $QUERIES_DIR/overview.sql"
echo ""
echo "2. Channel Analysis:"
echo "   sqlite3 -header -column $DB < $QUERIES_DIR/channels.sql | head -50"
echo ""
echo "3. Content Statistics:"
echo "   sqlite3 -header -column $DB < $QUERIES_DIR/content_stats.sql"
echo ""
echo "4. Embedding Progress:"
echo "   sqlite3 -header -column $DB < $QUERIES_DIR/embedding_progress.sql"
echo ""
echo "5. Evaluation Summary:"
echo "   sqlite3 -header -column $DB < $QUERIES_DIR/evaluation_summary.sql"
echo ""
echo "6. Data Quality Check:"
echo "   sqlite3 -header -column $DB < $QUERIES_DIR/data_quality.sql"
echo ""
echo "7. Trending Analysis:"
echo "   sqlite3 -header -column $DB < $QUERIES_DIR/trending_analysis.sql"
echo ""
echo "8. Search Test Status:"
echo "   sqlite3 -header -column $DB < $QUERIES_DIR/search_testing.sql"
echo ""
echo "Extended Analysis:"
echo ""
echo "9. API Cost Analysis:"
echo "   sqlite3 -header -column $DB < $QUERIES_DIR/cost_analysis.sql"
echo ""
echo "10. Algorithm Comparison:"
echo "    sqlite3 -header -column $DB < $QUERIES_DIR/comparison_queries.sql"
echo ""
echo "11. Export Reports (CSV/Markdown):"
echo "    sqlite3 -header -column $DB < $QUERIES_DIR/export_reports.sql | head -100"
echo ""
echo "Save any query to file:"
echo "   sqlite3 -header -column $DB < $QUERIES_DIR/overview.sql > report.txt"
echo ""
echo "Export as CSV:"
echo "   sqlite3 -header $DB < $QUERIES_DIR/channels.sql > channels.csv"
echo ""
echo "For more details, read: $QUERIES_DIR/README.md"
echo ""
